name: FACE PRODUCTION

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version:
          - 14
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run lint
        run: yarn lint
      - name: Run build
        run: yarn build

  deploy:
    runs-on: ubuntu-latest
    needs: [lint]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./
