name: FACE STAGING

on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    needs: build
    strategy:
      matrix:
        node-version:
          - 14
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run lint
        run: yarn lint
      - name: Run build
        run: yarn build
